name: test_env
channels:
  - conda-forge
dependencies:
  - pip
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - jupyter
  - ipywidgets
  - pip:
    - napari
    - trackpy
    - requests
    - pillow
    - image-processing
