name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - scikit-image>=0.16
  - pandas>=1.3.0
  - matplotlib>=3.4.1
  - napari >= 0.4.0
  - pip:
    - image-processing==0.0.0
    - pillow==9.0.1

