name: test_env
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - websockify
  - jupyter-server-proxy>=1.4
  - requests
  - scikit-image
  - pandas
  - matplotlib
  - pip:
    - jupyter-desktop-server
    - image-processing
    - pillow
    - napari[all]

