name: test_env
channels:
  - conda-forge
dependencies:
  - pip
  - scipy
  - numpy
  - matplotlib
  - pandas
  - scikit-image
  - scikit-learn
  - ipyvolume
  - nodejs
  - pip:
     - traittypes
     - traitlets
     - ipywidgets>=7.4
     - Pillow
     - scipy
     - numpy
     - scikit-image>=0.13
     - requests
     - ipywebrtc>=0.4
     - pythreejs>=1.0
     - matplotlib
     - jupyterlab>=0.34
     - notebook>=5.3
     - image-processing
